chi_squarex/urls.py
# Django Imports
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.shortcuts import redirect

# Standard Package Imports

# Project Imports
from . import settings

# Third Party Imports


urlpatterns = [
    path('admin/', admin.site.urls), # Namespace name is admin and path/url name is index for home page
    path('', include('main_app.urls', namespace='main_app'), name='main_app'), # To use dynamic urls "{% url 'namespace:url_name' %}"
    # path('', lambda x: redirect('/get_quote/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/urls.py
# Django Imports
from django import urls
from django.urls import path, include

# Standard Package Imports

# Project Imports
from . import views


# Third Party Imports


app_name = 'main_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('viewMembers', views.viewmembers, name='viewMembers'),
    path('members/<name>', views.members, name='members'),
    path('viewMembers', views.viewMembers, name='viewMembers'),
    path('publications', views.publications, name='publications'),
    path('form', views.form, name='form'),
    #path('get_quote/', views.get_quote, name='get_quote'),
    # path('<int:year>/', views.diary),
    # path('<int:year>/<str:name>/', views.diary),
]

urls.py
# Django Imports
from django import urls
from django.urls import path, include

# Standard Package Imports

# Project Imports
from . import views


# Third Party Imports


app_name = 'main_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('members/<name>', views.members, name='members'),
    path('viewMembers', views.viewMembers, name='viewMembers'),
    #path('get_quote/', views.get_quote, name='get_quote'),
    # path('<int:year>/', views.diary),
    # path('<int:year>/<str:name>/', views.diary),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'home/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!--Bootstrap CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

    <!-- Template Main CSS File -->
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/5f59ca6ad3.js" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}

</head>

<body>

    <!-- ======= Header ======= -->
  <header id="header" class="fixed-top bg-dark">
    <div class="container-fluid">

      <div class="row justify-content-center">
        <div class="col-xl-9 d-flex align-items-center justify-content-between">
          <h1 class="logo"><a href="/">Chi SquareX</a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html" class="logo"><img src="{% static 'home/img/logo.png' %}" alt="" class="img-fluid"></a>-->

          <nav class="nav-menu d-none d-lg-block">
            <ul>
              <li class="active"><a href="/">Home</a></li>
              <li><a href="/#about">About</a></li>
              <li><a href="/#services">Services</a></li>
              <li><a href="/#team">Team</a></li>
              <li><a href="/#pricing">Pricing</a></li>
              <li class="drop-down"><a href={% url 'main_app:form' %} target="_blank">Assignments</a>
                <ul>
                  <li><a href="#">Computer Science Assignments</a></li>
                  <li><a href="#">Computer Science Exams</a></li>
                  <li><a href="#">AI and ML Assignments</a></li>
                  <li><a href="#">AI and ML Exams</a></li>
                </ul>
              </li>
             <li class="drop-down"><a href="">Machine Learning Project</a>
                <ul>
                  <li><a href="#">Natural Language Processing</a></li>
                  <li><a href="#">Deep Learning</a></li>
                  <li><a href="#">Computer Vision</a></li>
                  
                </ul>
              </li>
              <li><a href={% url 'main_app:publications' %} target="_blank">Publications</a></li>
              <li><a href="#contact">Contact</a></li>

            </ul>
          </nav><!-- .nav-menu -->

          <a href="{% url 'admin:index' %}" class="get-started-btn scrollto">Admin Page</a>
        </div>
      </div>

    </div>
  </header><!-- End Header -->

    {% block body %}{% endblock %}

    <!-- ======= Footer ======= -->
    <footer id="footer" style="min-height:30vh;">
        <div class="container">
            <h3>Chi Squarex</h3>
            <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi
                placeat.</p>
            <div class="social-links">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
            <div class="copyright">
                &copy; Copyright <strong><span>ChiSquareX</span></strong>. All Rights Reserved
            </div>
            {% comment %} <div class="credits">
                Template by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div> {% endcomment %}
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'home/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'home/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'home/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'home/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'home/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'home/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'home/vendor/owl.carousel/owl.carousel.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'home/js/main.js' %}"></script>

    {% block js %}{% endblock %}

</body>

</html>

templates/form.html
{% extends 'base.html' %}
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    {% block head %}
    <title>Home | Chi Squarex</title>
  <link rel="shortcut icon" href="{% static 'home/img/chisquare.png' %}">
  <!-- Favicons -->
  <link href="{% static 'home/img/chisquare.png' %}" rel="icon">
  <link href="{% static 'home/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  <!--Members grid files-->
  <!-- Vendor CSS Files -->
  <link href="{% static 'home/members_assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'home/members_assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/members_assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
  <style>
    *{
        margin: 10px 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'popins', sans-serif;
    }
    
    
    .title1{
        font-family: 'Fredoka One', cursive;
        color: black;
    }
    
    
    #c1{
        max-width: 730px;
        width: 100%;
        background: white;
        padding: 25px 30px;
        border-radius: 10px;
    }
    
    #c1 .title1{
        font-size: 25px;
        font-weight: 500;
        position: relative;
    }
    
    #c1 #f11 .user-details{
          display: flex;
          flex-wrap: wrap;
          justify-content: space-between;
    }
    
    #f11 .user-details #ib1{
        margin: 20px 0 12px 0;
        width: calc(100% / 2- 20px);
    }
    .user-details #ib1 .details{
            display: block;
            font-weight: 500;
            margin-bottom: 20px;
    }
    
    .user-details #ib1 input{
        height: 40px;
        width: 100%;
        outline: none;
        border-radius: 5px;
        border: 2px solid black;
        padding: 15px;
        font-size: 16px;
    }
    
    .area{
        height: 90px;
        width: 120%;
        outline: none;
        border-radius: 5px;
        border: 2px solid black;
        padding: 10px;
        font-size: 20px;
    }
    
    .user-details #ib1 input:focus,
    .user-details #ib1 input:valid{
        border-color:black;
    }
    
    #f11 .user-details .filebox{
        margin: 20px 0 12px 0;
        width: calc(100% / 2- 20px);
    }
    .user-details .filebox {
            display: block;
            font-weight: 500;
            margin-bottom: 20px;
    }
    
    .user-details .filebox input{
        height: 52px;
        width: 95%;
        outline: none;
        border-radius: 5px;
        border: 2px solid black;
        padding: 15px;
        font-size: 16px;
    }
    
    .divfilebox{
        display: flex;
    }
    
    #f11 .button1{
        height:45px;
        width:45px 0;
    }
    #f11 .button1 input{
        margin-top: 15px;
        height:100%;
        width: 200%;
        
    }
    .details{
        text-align: initial;
        display: block;
        font-weight: 500;
    }
    
    
    
    @media (max-width:584px){
        .m1{
            height:auto;
        }
        #c1{
            max-width:100%;
            
        }
        .title1{
            margin-top: 5%;
        }
        #f11 .user-details #ib1{
            margin-bottom: 15px;
            width:100%;
        }
        #f11 .user-details .filebox{
            margin-bottom: 15px;
            width:100%;
        }
        
        
    }
    @media (max-width:700px){
        .area{
            width: 100%;
        }
    }

    header {
        top: -50px !important;
        height: 114px;
    }
  </style>
    {% endblock %}

  </head>
 

  <body>
    {% block body %}
    <br><br>
    <main id="main" class="m1">
    <section id="team" class="team">
<center>
        <div class="container" id="c1">
            <h2 style="width:75%;"><div class="title1"><strong >SUBMIT YOUR HOMEWORK ASSIGNMENT TO GET A FREE QUOTE FROM US.</strong></div></h2>
            <form id="f11" action="#">
              <div class="user-details">
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Full Name&nbsp;<strong style="color:red">*</strong></span>
                    <input type="text" style="border-top: none;border-right: none; border-left: none;border-radius: 0;" name="fname" required>
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Email ID&nbsp;<strong style="color:red">*</strong></span>
                    <input type="email" style="border-top: none;border-right: none; border-left: none;border-radius: 0;" name="mail" required>
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Mobile&nbsp;<strong style="color:red">*</strong></span>
                    <input type="tel" style="border-top: none;border-right: none; border-left: none;border-radius: 0;" name="mobile" required>
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Country&nbsp;<strong style="color:red">*</strong></span>
                    <input type="text" style="border-top: none;border-right: none; border-left: none;border-radius: 0;" name="country" required>
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;"> Subject&nbsp;<strong style="color:red">*</strong></span>
                    <input type="text" style="border-top: none;border-right: none; border-left: none;border-radius: 0;" name="subject" required>
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Deadline Date&nbsp;<strong style="color:red">*</strong></span>
                    <input type="date" style="border-top: none;border-right: none; border-left: none;border-radius: 0;" required id="start" name="trip-start" value="2021-01-01" min="2021-01-01" max="2100-12-31">
      
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Time&nbsp;<strong style="color:red">*</strong></span>
                    <input id="appt-time" style="border-top: none;border-right: none; border-left: none;border-radius: 0;" required type="time" name="appt-time" value="13:30">
                </div>
      
               
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;"> Topic&nbsp;<strong style="color:red">*</strong></span>
                    <input type="text" style="border-top: none;border-right: none; border-left: none;border-radius: 0; width:19rem;text-align: initial;padding-left: 0;" name="topic" placeholder="Ex- AI and ML assignment/exam">
                </div> 
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Other Instructions</span>
                    
                    <textarea  class="area" id="w3review" name="w3review" rows="4" cols="50" style="border-top: none;border-right: none; border-left: none;border-radius: 0;text-align: initial;padding-left: 0;">
                    </textarea>
      
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Expected Price(INR)&nbsp;<strong style="color:red">*</strong></span>
                    <input type="text" name="price" style="border-top: none;border-right: none; border-left: none;border-radius: 0;text-align: initial;padding-left: 0;" required>
                </div>
      
                <div class="input-box" id="ib1">
                    <span class="details" style="margin-bottom: 0;">Promocode</span>
                    <input type="text" name="pcode" style="border-top: none;border-right: none; border-left: none;border-radius: 0;text-align: initial;padding-left: 0;">
                </div>
            <div class="divfilebox">
                <div class="filebox ">
                    <span class="details" style="margin-bottom: 0;">Attach File 1&nbsp;<strong style="color:red">*</strong></span>
                    <input type="file" name="attachFile1" onblur="return chechExtension();" required>
                </div>
      
                <div class="filebox ">
                    <span class="details" style="margin-bottom: 0;">Attach File 2</span>
                    <input type="file" name="attachFile2" onblur="return chechExtension();" >
                </div>
              </div>
      
              <div class="divfilebox">
                <div class="filebox ">
                    <span class="details" style="margin-bottom: 0;">Attach File 3</span>
                    <input type="file" name="attachFile3" onblur="return chechExtension();" >
                </div>
      
                <div class="filebox ">
                    <span class="details"  style="margin-bottom: 0;">Attach File 4</span>
                    <input type="file" name="attachFile4" onblur="return chechExtension();" >
                </div>
              </div>
      
              <div class="button1" id="email1">
                  <input type="submit" id="sub1" style="border-radius: 2rem;background: #009961;color: white;border-color: white;" onclick="send()" value="SUBMIT">
                </div>
            </form>
          </div>
        </center>
          
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
          
  
      </section><!-- End Team Section -->
    {% endblock %}
    {% block js %}{% endblock %}
</main>
</body>    
</html>

templates/members.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <title>{{member.name}} | Chi Squarex</title>
    <!-- Favicons -->
    <link href="{% static 'home/img/favicon.png' %}" rel="icon">
    <link href="{% static 'home/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
    <link href="{% static 'members/styles.css' %}" rel="stylesheet">
    {% endblock %}
</head>

<body>
    {% block body %}
    <div class="main-bg-container">
        <div class="container mt-5 pt-5 pb-4">
            <div class="row">
                <div class="col-12 col-lg-5 d-flex flex-column">
                    <img src="{{member.image.url}}" class="member-image" />
                    <div class="d-flex flex-row justify-content-center mt-2">
                        <a href="{{member.facebook}}">
                            <i class="fab fa-facebook-square social-icon"></i>
                        </a>
                        <a href="{{member.instagram}}">
                            <i class="fab fa-instagram social-icon ml-4"></i>
                        </a>
                        <a href="{{member.linkedin}}">
                            <i class="fab fa-linkedin social-icon ml-4"></i>
                        </a>
                        <a href="https://wa.me/91{{member.whatsapp}}">
                            <i class="fab fa-whatsapp social-icon ml-4"></i>
                        </a>
                    </div>
                </div>
                <div class="col-12 col-lg-7 pt-2 member-info">
                    <h1 class="member-name">
                        {{member.name}}<span class="member-designation ml-3">{{member.designation}}</span>
                    </h1>
                    <p class="member-description">{{member.description}}</p>
                    {% if member.project_details %}
                    <h1 class="member-work-heading">
                        Project Details
                    </h1>
                    <pre class="member-work-description">{{member.project_details}}</pre>
                    {% endif %}
                    {% if member.research_work %}
                    <h1 class="member-work-heading">
                        Research Work
                    </h1>
                    <p class="member-work-description">{{member.research_work}}</p>
                    {% endif %}
                </div>
            </div>

        </div>

    </div>


    {% endblock %}
    {% block js %}{% endblock %}
</body>

</html>

templates/viewMembers.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <title>{{member.name}} | Chi Squarex</title>
    <!-- Favicons -->
    <link href="{% static 'home/img/favicon.png' %}" rel="icon">
    <link href="{% static 'home/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
    <link href="{% static 'members/styles.css' %}" rel="stylesheet">
    <link href="{% static 'home/members_assets/css/style.css' %}" rel="stylesheet">

    {% endblock %}
</head>

<body>
    {% block body %}
    <br><br>
    <main id="main">
    <section id="team" class="team">

        <div class="container" data-aos="fade-up">
  
          <header class="section-header">
            <!-- <h2>Team</h2> -->
            <p>Our hard working team</p>
          </header>
  
          <div class="row gy-4">
            {% for member in members %}
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch mb-4" data-aos="fade-up" data-aos-delay="100">
              <div class="member">
                <div class="member-img">
                  <img src="{{member.image.url}}" class="img-fluid" alt="">
                  <div class="social">
                    <a href="{% url 'main_app:members' member.name %}"><i class="fas fa-address-card"></i></a>
                    <a href="{{member.facebook}}"><i class="fab fa-facebook-square"></i></a>
                    <a href="{{member.instagram}}"><i class="fab fa-instagram"></i></a>
                    <a href="{{member.linkedin}}"><i class="fab fa-linkedin"></i></a>
                    <a href="https://wa.me/91{{member.whatsapp}}"><i class="fab fa-whatsapp"></i></a>
                  </div>
                </div>
                <div class="member-info">
                  <h4>{{member.name}}</h4>
                  <span>{{member.designation}}</span>
                  <p>
                    {{member.description}}
                  </p>
                </div>
              </div>
            </div>
            {% endfor %}
  
          </div>
        </div>
  
      </section><!-- End Team Section -->
    {% endblock %}
    {% block js %}{% endblock %}
</main>
</body>

</html>